dist: focal
language: java
jdk:
  - oraclejdk15

before_deploy:
  - mvn assembly:single
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "target/S-Plan_SchildConnnector-jar-with-dependencies.jar"
  skip_cleanup: true
  draft: true

after_deploy:
  - docker build -t docker.pkg.github.com/nils-witt/s-plan_schild/s-plan_schild:"$DOCKER_TAG" .
  - docker tag docker.pkg.github.com/nils-witt/s-plan_schild/s-plan_schild:"$DOCKER_TAG" docker.pkg.github.com/nils-witt/s-plan_schild/s-plan_schild:"$TRAVIS_COMMIT"
  - echo "$GITHUB_KEY" | docker login https://docker.pkg.github.com -u "$GITHUB_USER" --password-stdin
  - docker push docker.pkg.github.com/nils-witt/s-plan_schild/s-plan_schild