dist: focal
language: java
jdk:
  - oraclejdk15

before_install:
  - mvn assembly:single
  - ls target/
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "target/S-Plan_SchildConnnector-jar-with-dependencies.jar"
  skip_cleanup: true
  draft: true